### ISSUE TITLE
Having problem with using it

### ISSUE THREAD

**Issue by AliAliAl** [symmy596/PolyPy#1]
Hello Adam,

I have tried to use PolyPy but, did not work. Please, can you add more description on how to use it?
In addition, it would be great if you have a script to convert HISTORY file to PDB format that can be read in different packages. I tried with VMD but the results were as attached snapshot.
Thanks 
Ali

![selection_003](https://user-images.githubusercontent.com/34692220/44952374-58c2bf80-ae43-11e8-84a6-358bd90ab2ea.png)

**Comment by symmy596** [comment]
Hi Ali

Polypy is in early development at this stage and documentation is in development. Can you provide me with an idea of what you want to use it for? and any specific issues that you have encountered? Both would be a great help to me the developer. 

Cheers
